version: "3.7"
services:
  
  web:
    build: ./web_api/
    expose: 
      - "8080"
    volumes:
      - socket:/usr/src/app/flask_exam/
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
  
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    volumes:
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
        read_only: true
    environment:
      MYSQL_ROOT_PASSWORD: abcd123
      TZ: Asia/Taipei
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always

  nginx:
    build: ./nginx/
    ports: 
      - "80:80"
    volumes_from:
      - web
    links:
      - web:flask_exam
    depends_on:
      - web
    restart: always

volumes:
  socket: