version: "3.7"
services:
  web:
    build: ./web_api/ # Build 在同一資料夾的 Dockerfile（描述 Image 要組成的 yaml 檔案）成 container
    expose:
      - "8080"
    volumes:
      - ./web_api/flask_exam/:/usr/src/app/flask_exam/ # 要從本地資料夾 mount 掛載進去的資料
    links:
      - mysql
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: abcd123
      TZ: Asia/Taipei
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
        read_only: true
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
    - ./web_api/flask_exam/:/usr/src/app/flask_exam/
    volumes_from:
      - web
    links:
      - web:flask_exam
    depends_on:
      - web